# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - id: lsp
    binary: "kurtosis_lsp"
    main: ./cmd/starlark-lsp
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=1
      - CC={{ if index .Env "CC_WITH_DEFAULT" }}{{ .Env.CC_WITH_DEFAULT }}{{ else }} clang {{ end }}
      - CXX={{ if index .Env "CXX_WITH_DEFAULT" }}{{ .Env.CXX_WITH_DEFAULT }}{{ else }} clang++ {{ end }}
    flags:
      - -tags=osusergo
    overrides:
      - goos: linux
        goarch: arm64
        env:
          - CGO_ENABLED=1
          - CC=aarch64-linux-gnu-gcc
          - CXX=aarch64-linux-gnu-g++
      - goos: linux
        goarch: amd64
        goamd64: v1
        env:
          - CGO_ENABLED=1
          - CC=x86_64-linux-musl-gcc
          - CXX=x86_64-linux-musl-g++
        ldflags:
          - -linkmode external -extldflags "-static"
